### ISSUE TITLE
Fix WebUSB since Chromium 91

### ISSUE THREAD

**Issue by avbfr** [LedgerHQ/passwords-backup#1]
Hello,
The issue is probably the same as the one related here: [Problem with WebUSB + Chrome 91.X](https://github.com/LedgerHQ/ledgerjs/issues/607)

It looks like Ledger provided a fix : [https://repl.ledger.tools/](https://repl.ledger.tools/) 
Could it be applied to the password-backups webpage please ? 

Thanks !

Best Regards,
AVB

**Comment by burningd0g** [comment]
@avbfr i created a fork with package version fix that works and a pull request. don't know when (and if) it'll be merged.
you can review/clone (or down as zip and extract) my fork and run it locally if needed :
- install nodejs
- npm install --global yarn
- yarn install
- yarn start
